resources:
  repositories:
  - repository: pipeline-templates
    type: git
    name: Space Game - web - SonarCloud/pipeline-templates

trigger:
  - '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'

steps:
  - checkout: self
  - checkout: pipeline-templates
  
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
    inputs:
      packageType: sdk
      version: '$(dotnetSdkVersion)'

  - task: Npm@1
    displayName: 'Run npm install'
    inputs:
      verbose: false
  
  - script: 'pwd; ls -a;'
    displayName: 'Printing output to console'
  
  - script: './mslearn-tailspin-spacegame-web/node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
    displayName: 'Compile Sass assets'

  - task: gulp@1
    displayName: 'Run gulp tasks'

  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'Write build info'
    workingDirectory: $(wwwrootDir)

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - template: build-template.yml@pipeline-templates
    parameters:
      buildConfiguration: 'Debug'

#   - template: pipeline-templates/build.yml
#     parameters:
#       buildConfiguration: 'Release'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
